# Generated by Django 3.1.3 on 2020-12-15 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20201211_1727'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lists', '0003_auto_20201216_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='list', to='products.Product'),
        ),
        migrations.AlterField(
            model_name='list',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='list', to=settings.AUTH_USER_MODEL),
        ),
    ]
