# Generated by Django 3.1.3 on 2020-11-19 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201119_1202'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductType',
            new_name='ProductLanguage',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.AddField(
            model_name='product',
            name='product_language',
            field=models.ManyToManyField(blank=True, to='products.ProductLanguage'),
        ),
    ]
