# Generated by Django 3.1.3 on 2020-11-19 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20201119_1236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productlanguage',
            options={'ordering': ['name'], 'verbose_name_plural': 'Product Languages'},
        ),
        migrations.AlterModelOptions(
            name='producttype',
            options={'ordering': ['name'], 'verbose_name_plural': 'Product Types'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_language',
        ),
        migrations.AddField(
            model_name='product',
            name='product_language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productlanguage'),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('caption', models.CharField(max_length=80)),
                ('file', models.ImageField(upload_to='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
