# Generated by Django 3.1.3 on 2020-11-19 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20201119_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='address',
        ),
    ]
