# Generated by Django 3.1.3 on 2020-12-11 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='filename',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to='product_datas'),
        ),
        migrations.DeleteModel(
            name='Data',
        ),
    ]
