# Generated by Django 3.1.3 on 2020-12-11 08:27

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20201211_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to=products.models.get_file_path),
        ),
    ]
